-- These fields are present in the checked-in jOOQ model and used by repositories,
-- but older Flyway migrations did not create all of them on a clean database.
ALTER TABLE courses
  ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS description VARCHAR(1000);

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS note TEXT;
